version: '3.1'
services:
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datalogger
      MYSQL_USER: datalogger
      MYSQL_PASSWORD: datalogger
    ports:
    - 3306:3306